#!/bin/bash

# shellcheck source=assets/runtime/functions.sh
FUNCTIONS_FILE="${SALT_RUNTIME_DIR}/functions.sh"
source "${FUNCTIONS_FILE}"

log_info "Starting configuration reloader..."

while true; do
  if inotifywait -qq --event modify,move,create,delete "${SALT_CONFS_DIR}"; then
    log_info "Configuration changes detected. Reloading salt-master ..."
    supervisorctl restart salt-master
    log_info "Configuration reloaded."
  fi
done
